# Enable verbose output
verbose = true

# Enable entropy scanning
entropy = true

# Enable credential validation
only_verified = true

# Set the maximum depth of Git history to scan
max_depth = 100

# Define allowlist patterns to ignore known false positives
[[allowlist]]
regex = "ghp_exampleFakeToken1234567890"

[[allowlist]]
regex = "AKIAIOSFODNN7EXAMPLE"

# Optional: ignore specific file paths
[[path_allowlist]]
path = "docs/fake-secrets.txt"

# Optional: ignore specific commit authors
[[author_allowlist]]
author = "testuser@example.com"

# Optional: ignore specific commit messages
[[commit_message_allowlist]]
regex = "test commit with fake secrets"

# Optional: ignore specific branches
[[branch_allowlist]]
branch = "test-branch"
