entropy: true
only_verified: true
max_depth: 100

allowlist:
  - regex: "ghp_exampleFakeToken1234567890"
  - regex: "AKIAIOSFODNN7EXAMPLE"

path_allowlist:
  - path: "docs/fake-secrets.txt"

author_allowlist:
  - author: "testuser@example.com"

commit_message_allowlist:
  - regex: "test commit with fake secrets"

branch_allowlist:
  - branch: "test-branch"
